baseurl: "https://haktec.de"
title: "Tech Stuff"
languageCode: "en-us"
theme: "hemingway"
copyright: "&copy; 2015 Hannes Körber"

buildDrafts: false
buildFuture: false
buildExpired: false

disableRSS: true
enableEmoji: false

log: false

author:
  name: "Hannes Körber"

params:
  social:
    - url: "https://github.com/whatevsz"
      fa_icon: "fa-github"
    - url: "https://gitlab.com/whatevsz"
      fa_icon: "fa-gitlab"
    - url: "https://www.linkedin.com/in/hannes-k%C3%B6rber-479ab5122"
      fa_icon: "fa-linkedin"
    - url: "https://www.xing.com/profile/Hannes_Koerber?sc_o=mxb_p"
      fa_icon: "fa-xing"
    - url: "https://twitter.com/whatevsz"
      fa_icon: "fa-twitter"
    - url: "mailto:hannes.koerber@gmail.com)"
      fa_icon: "fa-envelope"
